version: "3.7"
services:
  jp-pg:
    build:
      context: ./jp-pg
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - jp_pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dockage/phppgadmin
    environment:
      - PHP_PG_ADMIN_SERVER_HOST=jp-pg
      - PHP_PG_ADMIN_SERVER_PORT=5432
    ports: 
      - 80:80
    depends_on:
      - jp-pg

volumes:
  jp_pg_data: